### ISSUE TITLE
Not working for me

### ISSUE THREAD

**Issue by mopoIo** [slinkstr/CytubeManifestGenerator#1]
When I drag my media on top of the .exe nothing happens.
I have the executable on my ffmpeg > bin folder, and nothing is happening.
How can I fix it?

**Comment by slinkstr** [comment]
I just published a release to show errors more clearly. If it still closes immediately and you can't read the output you can open command prompt and put your media as an argument, e.g.: `CytubeManifestGenerator-2.0.1-win64.exe C:\path\to\my_video.mp4`

Without more details I can only guess that there was spaces in the file path (fixed in 2.0.1).

Attach/link the media you're trying it with if you still have problems 🙂

**Comment by mopoIo** [comment]
Doing it thru cmd prompt showed me the error and now it worked! Thank you!

**Comment by mopoIo** [comment]
It did create the manifest but when I add it to CyTube I'm getting 'The media could not be loaded, either because the server or network failed or because the format is not supported.'

What am I doing wrong?
If I only add the video url it works, but when I try with the manifest I get that error

**Comment by slinkstr** [comment]
The console in your browser's devtools will have more info, the video player only shows a generic error.

**Comment by mopoIo** [comment]
![2023-01-27 18_00_53-offline chat tv — Mozilla Firefox](https://user-images.githubusercontent.com/41168773/215197180-933ba548-645c-4462-a880-951ff1273d16.png)

This is the error I'm getting, apologies for being in Spanish

**Comment by slinkstr** [comment]
The text track is being blocked by your browser, [as described in this note in the readme.](https://github.com/slinkstr/CytubeManifestGenerator#note)

There's nothing that the generator can do to fix this, since how to set this header depends on what web server you use.

If you're using NGINX (it looks like you are based on the URL in the error log), you just need to add this to your site config: `add_header "Access-Control-Allow-Origin" "https://cytu.be";`

**Comment by mopoIo** [comment]
I added the header and now the website is working but for some reason the player looks black, I hear the audio and see the subtitles, but I can't see the video? You think this is related to my file or is still something wrong? This is where I'm testing it in case you want to take a look: https://cytu.be/r/7tv

**Comment by slinkstr** [comment]
The video you're trying to use is HEVC/H265. [HEVC isn't supported by every major browser yet.](https://caniuse.com/hevc) Re-encode and use x264/h264 for best compatibility.

**Comment by mopoIo** [comment]
Thank you so much! I'll go ahead and close this issue. Thanks for the help.
